### ISSUE TITLE
How do you manage balance between your regular coding job, your music job and private life?

### ISSUE THREAD

**Issue by anselmh** [kahlil/ama#2]
I wonder how you manage to keep balance of your job as a coder, as music manager/producer (think this is what you do, otherwise correct me?) and your private life.
Also, do you have goals regarding each job? Will you drop one at some point?

**Comment by khalillechelt** [comment]
Before I answer this question, some clarification on how I am involved in music.

I have been making music as a vocalist, performer and writer semi-professional and professional for about 10 years before I even started working as a coder around seven and a half years ago. Semi professional during my studies and full-time after my studies.

After doing music full-time I have been involved in musical projects in multiple ways next to my full time job as a web developer. In all of them I am participating either by adding value to the production through feedback to music and/or lyrics or by contributing with lyrics and/or recording/performing myself.

I believe you may think that I am a manager/producer because my Twitter bio once stated that I am an executive producer on the [Agent Lexie project](http://soundcloud.com/agentlexie), my wife's musical project.

This was the case because my activities in that project were exactly that of an executive producer: enabling the project through financial contribution and participating in the projects conceptually, contributing to the production by helping to shape the sound with feedback.

During the production of the album I often joined the producer of the album and my wife in the studio after work to listen to what they had done and talk about it. I also sometimes helped with the writing but not very often at all since my wife is a much better writer than I am. It took around two years to complete the album.

I am not and never was a manager. I don't possess the skills a manager to an artist needs to have. Last year during an Agent Lexie club tour through Germany and a project with a production team in Berlin I had to kind of take on some managerial tasks for the project, but honestly I'd rather have not.

During the production of the album and during the club tour and the production collab last year I put in a lot of hours after work and on weekends. There is just no way how you can be involved in projects like that next to work and have a lot of free time. It took quite a toll on me.

Next to my wife's project, which does not require a lot of time from my side currently, I am now meeting with [my brother](http://twitter.com/bonotes) on a regular basis to work on music. He produces the music I provide lyrics and record on the music. We used to work on that stuff on and off for two years, Since the beginning of this year we are meeting once a week on Thursdays after work for about 2 to 4 hours. We are planning to release something pretty soon.

During the months before JSConf EU in which we worked on the JSConf performance with @janmonschke, my brother and I met twice a week and sometimes on the weekend to get it done.

On top of that I am also involved in another project for which me and my wife are providing lyrics and record on their music. That project has also been ongoing for years and is now slowly coming to a release. For me that project entailed meeting with friends in the studio every now and then after work and recording lyrics I wrote mostly during my commute to and from work.

So as you can see I am not shy to invest time into music after work. But this of course is also the case because music is not "work" for me. Making music has been a part of my life since I was 12 or something, I am not sure when that started but I will always be making music in some capacity, because I must. It is part of the fabric of me.

But of course I can't be doing only that in my free time. Currently between 2 to 4 evenings during the week are dedicated to making music or podcasting. Wednesday we record [Reactive](http://reactive.audio) and Thursdays I meet with my brother. Other evenings may be occupied recording [Descriptive](http://descriptive.audio) or working on other musical or web projects but currently that has slowed down. 

If there is no special projects like the [JSConf EU performance](https://www.youtube.com/watch?v=lJ1kY-CSpBk) or a tour my wife is doing etc. the weekends are free and I spend them mostly with my wife.
Keeping the weekends as free as possible is important to me but being actively involved in music is too.

I like doing music on the side though, it enables me to take my time with the projects and make sure that what we do has the quality me and my collaborators want to see. Making music with the pressure of having to make money was the worst.

I love web development as well and so far I have no plans to drop any of those two "jobs" :smile:

When it comes to coding my goal is to keep getting better at JavaScript and building apps. I am really intrigued by the possibilities of JavaScript applications that also work offline. 

In music my goal is to make the best music I can in the projects I am involved in. I am lucky to be able to work with some pretty amazing people in the field. I feel like I have learned a lot from my wife and I have grown as a lyricist and a performer and I want to keep improving in those areas as well.

**Comment by anselmh** [comment]
Wow, quite a lengthy and detailed answer. Thank you so much! :)

**Comment by khalillechelt** [comment]
:smile: thank you for the question! It was fun to answer it.
