### ISSUE TITLE
Dev setup

### ISSUE THREAD

**Issue by Traverso** [kahlil/ama#5]
Hi Kahlil,
What is your current/preferred setup for front-end development - automation tools, tests & deployment?
Does it make a difference is it's a pet project/internal tool or if it something for a customer?

**Comment by khalillechelt** [comment]
> What is your current/preferred setup for front-end development - automation tools, tests & deployment?

My favorite setup is using Atom as an editor and use npm for the rest.

Since I looked into using npm as a task runner I can't really use anything else anymore. It is so easy to get going and it is so powerful.

When it comes to testing it depends what I am working on, if it is a little Node package I like using `tape`. At work we are building an Angular app and just use Protractor, Jasmine, Karma. As you should.

When it comes to deployment it really depends on what the project needs. For small personal projects I just rsync (triggered via `npm run`) or use the CLI from @surge_sh to deploy a site. At work we are using Jenkins to deploy our code. For bigger personal projects I'd most likely use Github/Travis for deployment but I did not need that setup yet.

> Does it make a difference if it's a pet project/internal tool or if it something for at customer?

I don't have clients currently but if I did, I would just use npm as a task runner as well and then see how far it takes me. npm for all the things, it's amazing.

At work we are currently using Gulp as a task runner. It is quite a complicated setup and I don't know if just using npm as a task runner would be enough in this case. Gulp serves as well in that scenario. 

Does this answer your questions?

**Comment by Traverso** [comment]
Thanks! Seems like I have to give npm a second look

**Comment by Traverso** [comment]
For others interesting in npm as a task runner, this are a couple of resources that Kahlil pointed out on twitter:
https://github.com/keithamus/npm-scripts-example
https://github.com/kahlil/kahlil.info/blob/master/package.json

And this are a couple of blogs about this approach:
http://blog.teamtreehouse.com/use-npm-task-runner
http://beletsky.net/2015/04/npm-for-everything.html

and from the lion's (wombat) mouth:
http://paulcpederson.com/articles/npm-run/

**Comment by khalillechelt** [comment]
Also see this excellent intro to npm scripts: https://github.com/hoodiehq/hoodie-css/blob/feature/build-automation/DEVELOPMENT.md
